2025-05-03 19:50:43,897 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-03 19:50:44,073 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] Se encontraron 2 tablas.
2025-05-03 19:50:44,075 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] 
üìÑ Tabla: public.detalle_usuarios
2025-05-03 19:50:44,171 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py]     - id_detalle_usuarios (integer, NULLABLE: NO)
2025-05-03 19:50:44,175 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py]     - id_usuario (integer, NULLABLE: NO)
2025-05-03 19:50:44,178 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py]     - contrasena (text, NULLABLE: NO)
2025-05-03 19:50:44,182 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py]     - token (text, NULLABLE: YES)
2025-05-03 19:50:44,184 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py]     - grupo (integer, NULLABLE: NO)
2025-05-03 19:50:44,190 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py]     - email (character varying, NULLABLE: NO)
2025-05-03 19:50:44,195 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py]     - estado_cuenta (boolean, NULLABLE: NO)
2025-05-03 19:50:44,290 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py]     üîë PRIMARY KEY: id_detalle_usuarios
2025-05-03 19:50:44,384 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] 
üìÑ Tabla: public.usuarios
2025-05-03 19:50:44,473 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py]     - id_usuario (integer, NULLABLE: NO)
2025-05-03 19:50:44,475 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py]     - nick_name (character varying, NULLABLE: NO)
2025-05-03 19:50:44,477 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py]     - fecha (date, NULLABLE: NO)
2025-05-03 19:50:44,568 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py]     üîë PRIMARY KEY: id_usuario
2025-05-03 19:50:44,660 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] Exploraci√≥n de estructura completada correctamente.
2025-05-03 19:50:44,668 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-03 19:50:44,673 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Exploraci√≥n finalizada.
2025-05-03 23:28:12,549 - ERROR - Archivo: log.py - L√≠nea: 152 - [ERROR] [<frozen runpy>] ‚ùå Error al ejecutar manualmente: cannot import name 'Conexiona_Data_Base' from 'Clases_Base.Conexion_Data_Base' (C:\Users\USER\Documents\Unipamplona\Semestre_10\Seguridad  Informatica\Proyecto_APG\Proyecto_APG\Clases_Base\Conexion_Data_Base.py)
2025-05-03 23:29:59,603 - ERROR - Archivo: log.py - L√≠nea: 152 - [ERROR] [<frozen runpy>] ‚ùå Error al ejecutar manualmente: cannot import name 'Conexiona_Data_Base' from 'Clases_Base.Conexion_Data_Base' (C:\Users\USER\Documents\Unipamplona\Semestre_10\Seguridad  Informatica\Proyecto_APG\Proyecto_APG\Clases_Base\Conexion_Data_Base.py)
2025-05-03 23:31:03,234 - ERROR - Archivo: log.py - L√≠nea: 152 - [ERROR] [<frozen runpy>] ‚ùå Error al ejecutar manualmente: cannot import name 'Conexiona_Data_Base' from 'Clases_Base.Conexion_Data_Base' (C:\Users\USER\Documents\Unipamplona\Semestre_10\Seguridad  Informatica\Proyecto_APG\Proyecto_APG\Clases_Base\Conexion_Data_Base.py)
2025-05-03 23:32:21,817 - ERROR - Archivo: log.py - L√≠nea: 152 - [ERROR] [<frozen runpy>] ‚ùå Error al ejecutar manualmente: cannot import name 'Crud_Usuario_Detalle' from 'Clases_Base.Crud_Usuario_Detalle' (C:\Users\USER\Documents\Unipamplona\Semestre_10\Seguridad  Informatica\Proyecto_APG\Proyecto_APG\Clases_Base\Crud_Usuario_Detalle.py)
2025-05-03 23:33:06,193 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-03 23:33:06,196 - ERROR - Archivo: log.py - L√≠nea: 152 - [ERROR] [main_test.py] ‚ùå Error en el CRUD test: 'CrudUsuarioDetalle' object has no attribute 'crear_usuario_detalle'
2025-05-03 23:33:06,197 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-03 23:33:06,198 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] CRUD test finalizado.
2025-05-03 23:34:05,933 - ERROR - Archivo: log.py - L√≠nea: 152 - [ERROR] [main_test.py] ‚ùå Error en el CRUD test: 'CrudUsuarioDetalle' object has no attribute 'crear_usuario_detalle'
2025-05-03 23:34:05,936 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] CRUD test finalizado.
2025-05-03 23:34:26,426 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-03 23:34:26,428 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Iniciando inserci√≥n de nuevo usuario y detalle...
2025-05-03 23:34:26,430 - ERROR - Archivo: log.py - L√≠nea: 152 - [ERROR] [main_test.py] Error general al crear usuario: CrudUsuarioDetalle.generar_hash_contrasena() takes 1 positional argument but 2 were given
2025-05-03 23:34:26,431 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-03 23:34:26,433 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Transacci√≥n de creaci√≥n de usuario finalizada.
2025-05-03 23:34:26,434 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Usuario creado correctamente.
2025-05-03 23:34:26,436 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] CRUD test ejecutado correctamente.
2025-05-03 23:34:26,438 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] CRUD test finalizado.
2025-05-03 23:37:21,027 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-03 23:37:21,028 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Iniciando lectura de usuarios y sus detalles...
2025-05-03 23:37:21,196 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] Se recuperaron 2 registros de usuarios con detalles.
2025-05-03 23:37:21,199 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-03 23:37:21,201 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Lectura de usuarios con detalles finalizada.
2025-05-03 23:37:21,204 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] CRUD test ejecutado correctamente.
2025-05-03 23:37:21,206 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] CRUD test finalizado.
2025-05-03 23:39:56,060 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-03 23:39:56,062 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Iniciando inserci√≥n de nuevo usuario y detalle...
2025-05-03 23:39:56,063 - ERROR - Archivo: log.py - L√≠nea: 152 - [ERROR] [main_test.py] Error general al crear usuario: CrudUsuarioDetalle.generar_hash_contrasena() takes 1 positional argument but 2 were given
2025-05-03 23:39:56,065 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-03 23:39:56,066 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Transacci√≥n de creaci√≥n de usuario finalizada.
2025-05-03 23:39:56,068 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Usuario creado correctamente.
2025-05-03 23:39:56,076 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] CRUD test ejecutado correctamente.
2025-05-03 23:39:56,080 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] CRUD test finalizado.
2025-05-03 23:43:30,577 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-03 23:43:30,578 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Iniciando inserci√≥n de nuevo usuario y detalle...
2025-05-03 23:43:30,580 - ERROR - Archivo: log.py - L√≠nea: 152 - [ERROR] [main_test.py] Error general al crear usuario: CrudUsuarioDetalle.generar_hash_contrasena() takes 1 positional argument but 2 were given
2025-05-03 23:43:30,581 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-03 23:43:30,583 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Transacci√≥n de creaci√≥n de usuario finalizada.
2025-05-03 23:43:30,584 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Usuario creado correctamente.
2025-05-03 23:43:30,585 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] CRUD test ejecutado correctamente.
2025-05-03 23:43:30,587 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] CRUD test finalizado.
2025-05-03 23:47:35,368 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-03 23:47:35,374 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Iniciando inserci√≥n de nuevo usuario y detalle...
2025-05-03 23:47:35,769 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Usuario creado con ID: 4
2025-05-03 23:47:35,949 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] Usuario y detalle insertados correctamente.
2025-05-03 23:47:35,954 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-03 23:47:35,956 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Transacci√≥n de creaci√≥n de usuario finalizada.
2025-05-03 23:47:35,958 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Usuario creado correctamente.
2025-05-03 23:47:35,961 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] CRUD test ejecutado correctamente.
2025-05-03 23:47:35,963 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] CRUD test finalizado.
2025-05-04 00:02:37,861 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-04 00:02:37,862 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Iniciando lectura de usuarios y sus detalles...
2025-05-04 00:02:38,048 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] Se recuperaron 3 registros de usuarios con detalles.
2025-05-04 00:02:38,051 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-04 00:02:38,054 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Lectura de usuarios con detalles finalizada.
2025-05-04 00:02:38,057 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] CRUD test ejecutado correctamente.
2025-05-04 00:02:38,059 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] CRUD test finalizado.
2025-05-04 00:03:46,324 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-04 00:03:46,326 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Iniciando b√∫squeda del usuario con ID 4...
2025-05-04 00:03:46,578 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] Consulta completada para usuario ID 4.
2025-05-04 00:03:46,583 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-04 00:03:46,586 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Finalizaci√≥n de consulta de usuario.
2025-05-04 00:03:46,587 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] CRUD test ejecutado correctamente.
2025-05-04 00:03:46,591 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] CRUD test finalizado.
2025-05-04 00:06:13,761 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-04 00:06:13,764 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Iniciando actualizaci√≥n del usuario 4...
2025-05-04 00:06:14,258 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Tabla 'detalle_usuarios' actualizada.
2025-05-04 00:06:14,346 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] Usuario con ID 4 actualizado correctamente.
2025-05-04 00:06:14,349 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-04 00:06:14,350 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Transacci√≥n de actualizaci√≥n finalizada.
2025-05-04 00:06:14,351 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] CRUD test ejecutado correctamente.
2025-05-04 00:06:14,353 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] CRUD test finalizado.
2025-05-04 00:06:56,331 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-04 00:06:56,332 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Iniciando b√∫squeda del usuario con ID 4...
2025-05-04 00:06:56,587 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] Consulta completada para usuario ID 4.
2025-05-04 00:06:56,591 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-04 00:06:56,596 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Finalizaci√≥n de consulta de usuario.
2025-05-04 00:06:56,601 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] CRUD test ejecutado correctamente.
2025-05-04 00:06:56,605 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] CRUD test finalizado.
2025-05-04 02:05:33,921 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-04 02:05:33,941 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Verificando existencia de usuario...
2025-05-04 02:05:34,315 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] Login exitoso.
2025-05-04 02:05:34,315 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-04 02:05:34,321 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Proceso de login finalizado.
2025-05-04 02:05:34,323 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] Test de login ejecutado correctamente.
2025-05-04 02:05:34,323 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Test de login finalizado.
2025-05-04 14:49:25,267 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Iniciando generaci√≥n de token para correo 'carjisar@gmail.com'...
2025-05-04 14:49:25,272 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Link generado: http://localhost:5000/verificar/ImNhcmppc2FyQGdtYWlsLmNvbSI.aBfExQ.GoMO1d3bh466wkljRTNe6z_ZOzQ
2025-05-04 14:49:25,279 - ERROR - Archivo: log.py - L√≠nea: 152 - [ERROR] [main_test.py] Error al enviar correo: cannot import name 'mail' from 'app' (C:\Users\USER\Documents\Unipamplona\Semestre_10\Seguridad  Informatica\Proyecto_APG\Proyecto_APG\app.py)
2025-05-04 14:49:25,279 - ERROR - Archivo: log.py - L√≠nea: 152 - [ERROR] [main_test.py] ‚ùå El env√≠o de correo no fue exitoso.
2025-05-04 14:49:25,281 - ERROR - Archivo: log.py - L√≠nea: 152 - [ERROR] [<frozen runpy>] ‚ùå Error al ejecutar manualmente: 
2025-05-04 14:52:25,074 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Iniciando generaci√≥n de token para correo 'carjisar@gmail.com'...
2025-05-04 14:52:25,076 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Link generado: http://localhost:5000/verificar/ImNhcmppc2FyQGdtYWlsLmNvbSI.aBfFeQ.sJ1cABuLf20RbqRrGWyp4C0tixo
2025-05-04 14:52:25,084 - ERROR - Archivo: log.py - L√≠nea: 152 - [ERROR] [main_test.py] Error al enviar correo: cannot import name 'mail' from 'app' (C:\Users\USER\Documents\Unipamplona\Semestre_10\Seguridad  Informatica\Proyecto_APG\Proyecto_APG\app.py)
2025-05-04 14:52:25,086 - ERROR - Archivo: log.py - L√≠nea: 152 - [ERROR] [main_test.py] ‚ùå El env√≠o de correo no fue exitoso.
2025-05-04 14:52:25,088 - ERROR - Archivo: log.py - L√≠nea: 152 - [ERROR] [<frozen runpy>] ‚ùå Error al ejecutar manualmente: 
2025-05-04 14:55:38,612 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Iniciando generaci√≥n de token para correo 'carjisar@gmail.com'...
2025-05-04 14:55:38,612 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Link generado: http://localhost:5000/verificar/ImNhcmppc2FyQGdtYWlsLmNvbSI.aBfGOg.7MAkyIKaY1LC40_eHaZ_b8IjIR0
2025-05-04 14:55:38,618 - ERROR - Archivo: log.py - L√≠nea: 152 - [ERROR] [main_test.py] Error al enviar correo: cannot import name 'mail' from 'app' (C:\Users\USER\Documents\Unipamplona\Semestre_10\Seguridad  Informatica\Proyecto_APG\Proyecto_APG\app.py)
2025-05-04 14:55:38,620 - ERROR - Archivo: log.py - L√≠nea: 152 - [ERROR] [main_test.py] ‚ùå El env√≠o de correo no fue exitoso.
2025-05-04 14:55:38,622 - ERROR - Archivo: log.py - L√≠nea: 152 - [ERROR] [<frozen runpy>] ‚ùå Error al ejecutar manualmente: 
2025-05-04 15:00:00,598 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Iniciando generaci√≥n de token para correo 'carjisar@gmail.com'...
2025-05-04 15:00:00,606 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Link generado: http://localhost:5000/verificar/ImNhcmppc2FyQGdtYWlsLmNvbSI.aBfHQA.GXcMRwoVxsOVJz2UXG5EGuaZVSw
2025-05-04 15:00:03,926 - ERROR - Archivo: log.py - L√≠nea: 152 - [ERROR] [main_test.py] Error al enviar correo: (535, b'5.7.8 Username and Password not accepted. For more information, go to\n5.7.8  https://support.google.com/mail/?p=BadCredentials 00721157ae682-708c4680d24sm18056727b3.75 - gsmtp')
2025-05-04 15:00:03,928 - ERROR - Archivo: log.py - L√≠nea: 152 - [ERROR] [main_test.py] ‚ùå El env√≠o de correo no fue exitoso.
2025-05-04 15:00:03,928 - ERROR - Archivo: log.py - L√≠nea: 152 - [ERROR] [<frozen runpy>] ‚ùå Error al ejecutar manualmente: 
2025-05-04 15:00:50,348 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Iniciando generaci√≥n de token para correo 'carjisar@gmail.com'...
2025-05-04 15:00:50,355 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Link generado: http://localhost:5000/verificar/ImNhcmppc2FyQGdtYWlsLmNvbSI.aBfHcg.5r92bwGaimxajJ_4qq7cITElA80
2025-05-04 15:00:53,522 - ERROR - Archivo: log.py - L√≠nea: 152 - [ERROR] [main_test.py] Error al enviar correo: (535, b'5.7.8 Username and Password not accepted. For more information, go to\n5.7.8  https://support.google.com/mail/?p=BadCredentials 3f1490d57ef6-e755e7a873csm1656251276.43 - gsmtp')
2025-05-04 15:00:53,522 - ERROR - Archivo: log.py - L√≠nea: 152 - [ERROR] [main_test.py] ‚ùå El env√≠o de correo no fue exitoso.
2025-05-04 15:00:53,522 - ERROR - Archivo: log.py - L√≠nea: 152 - [ERROR] [<frozen runpy>] ‚ùå Error al ejecutar manualmente: 
2025-05-04 15:01:51,175 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Iniciando generaci√≥n de token para correo 'carjisar@gmail.com'...
2025-05-04 15:01:51,177 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Link generado: http://localhost:5000/verificar/ImNhcmppc2FyQGdtYWlsLmNvbSI.aBfHrw.Xc1H0gwfinxrnF5B0HL-fHaTT-0
2025-05-04 15:01:54,178 - ERROR - Archivo: log.py - L√≠nea: 152 - [ERROR] [main_test.py] Error al enviar correo: (535, b'5.7.8 Username and Password not accepted. For more information, go to\n5.7.8  https://support.google.com/mail/?p=BadCredentials 00721157ae682-708c3f08040sm18163487b3.5 - gsmtp')
2025-05-04 15:01:54,180 - ERROR - Archivo: log.py - L√≠nea: 152 - [ERROR] [main_test.py] ‚ùå El env√≠o de correo no fue exitoso.
2025-05-04 15:01:54,182 - ERROR - Archivo: log.py - L√≠nea: 152 - [ERROR] [<frozen runpy>] ‚ùå Error al ejecutar manualmente: 
2025-05-04 15:05:46,937 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Iniciando generaci√≥n de token para correo 'carjisar@gmail.com'...
2025-05-04 15:05:46,952 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Link generado: http://localhost:5000/verificar/ImNhcmppc2FyQGdtYWlsLmNvbSI.aBfImg._2ReyuYrRL5wgLl6rNK7klBulMM
2025-05-04 15:05:50,140 - ERROR - Archivo: log.py - L√≠nea: 152 - [ERROR] [main_test.py] Error al enviar correo: (535, b'5.7.8 Username and Password not accepted. For more information, go to\n5.7.8  https://support.google.com/mail/?p=BadCredentials 00721157ae682-708c3f3cebbsm18304277b3.29 - gsmtp')
2025-05-04 15:05:50,142 - ERROR - Archivo: log.py - L√≠nea: 152 - [ERROR] [main_test.py] ‚ùå El env√≠o de correo no fue exitoso.
2025-05-04 15:05:50,142 - ERROR - Archivo: log.py - L√≠nea: 152 - [ERROR] [<frozen runpy>] ‚ùå Error al ejecutar manualmente: 
2025-05-04 15:07:00,607 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Iniciando generaci√≥n de token para correo 'carjisar@gmail.com'...
2025-05-04 15:07:00,607 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Link generado: http://localhost:5000/verificar/ImNhcmppc2FyQGdtYWlsLmNvbSI.aBfI5A.A4Wi1rIxXnw__4ZnO4Qgyz_H5gE
2025-05-04 15:07:03,636 - ERROR - Archivo: log.py - L√≠nea: 152 - [ERROR] [main_test.py] Error al enviar correo: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2025-05-04 15:07:03,642 - ERROR - Archivo: log.py - L√≠nea: 152 - [ERROR] [main_test.py] ‚ùå El env√≠o de correo no fue exitoso.
2025-05-04 15:07:03,642 - ERROR - Archivo: log.py - L√≠nea: 152 - [ERROR] [<frozen runpy>] ‚ùå Error al ejecutar manualmente: 
2025-05-04 15:08:27,906 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Iniciando generaci√≥n de token para correo 'carjisar@gmail.com'...
2025-05-04 15:08:27,912 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Link generado: http://localhost:5000/verificar/ImNhcmppc2FyQGdtYWlsLmNvbSI.aBfJOw.aH__cKvpLECd55Jq6s__tYYvLdU
2025-05-04 15:08:32,228 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] Correo de verificaci√≥n enviado correctamente a 'carjisar@gmail.com'.
2025-05-04 15:08:32,228 - ERROR - Archivo: log.py - L√≠nea: 152 - [ERROR] [main_test.py] ‚ùå El env√≠o de correo no fue exitoso.
2025-05-04 15:08:32,234 - ERROR - Archivo: log.py - L√≠nea: 152 - [ERROR] [<frozen runpy>] ‚ùå Error al ejecutar manualmente: 
2025-05-04 15:18:51,964 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-04 15:18:51,964 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Verificando existencia de usuario...
2025-05-04 15:18:52,341 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] Login exitoso.
2025-05-04 15:18:52,344 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-04 15:18:52,344 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Proceso de login finalizado.
2025-05-04 15:18:52,344 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] ‚úÖ Test de login ejecutado correctamente.
2025-05-04 15:18:52,349 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] üß™ Test de login finalizado.
2025-05-04 15:18:52,354 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Iniciando generaci√≥n de token para correo 'carjisar@gmail.com'...
2025-05-04 15:18:52,359 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Link generado: http://localhost:5000/verificar/ImNhcmppc2FyQGdtYWlsLmNvbSI.aBfLrA.OjYWltPIfI6adJpEozarArTVBmc
2025-05-04 15:18:58,194 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] Correo de verificaci√≥n enviado correctamente a 'carjisar@gmail.com'.
2025-05-04 15:18:58,194 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] ‚úÖ Test de env√≠o de correo ejecutado correctamente.
2025-05-04 15:18:58,201 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] üß™ Test de env√≠o de correo finalizado.
2025-05-04 15:18:58,203 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Iniciando generaci√≥n de token para correo 'carjisar@gmail.com'...
2025-05-04 15:18:58,204 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Link generado: http://localhost:5000/verificar/ImNhcmppc2FyQGdtYWlsLmNvbSI.aBfLsg.67eZz4LsUrPrUJ6xeBPj_dA4xBI
2025-05-04 15:19:02,366 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] Correo de verificaci√≥n enviado correctamente a 'carjisar@gmail.com'.
2025-05-04 15:19:02,368 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Iniciando verificaci√≥n de token...
2025-05-04 15:19:02,390 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Token v√°lido para correo 'carjisar@gmail.com'. Procediendo a activar cuenta...
2025-05-04 15:19:03,120 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-04 15:19:03,144 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Iniciando actualizaci√≥n del usuario por 'd.email' = 'carjisar@gmail.com'...
2025-05-04 15:19:03,415 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Tabla 'detalle_usuarios' actualizada.
2025-05-04 15:19:03,507 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [GestionLogin.py] Usuario actualizado correctamente con ID 5.
2025-05-04 15:19:03,514 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-04 15:19:03,521 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Transacci√≥n de actualizaci√≥n finalizada.
2025-05-04 15:19:03,532 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] Cuenta verificada exitosamente.
2025-05-04 15:19:03,540 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] ‚úÖ Test de verificaci√≥n de cuenta ejecutado correctamente.
2025-05-04 15:19:03,555 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] üß™ Test de verificaci√≥n de cuenta finalizado.
2025-05-04 17:00:10,304 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-04 17:00:10,306 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Iniciando b√∫squeda del usuario por 'd.email' = 'carjisar@gmail.com'...
2025-05-04 17:00:10,474 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] Consulta completada para el id_usuario 'carjisar@gmail.com'.
2025-05-04 17:00:10,477 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-04 17:00:10,479 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Finalizaci√≥n de consulta de usuario.
2025-05-04 17:00:10,480 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] ‚úÖ Usuario consultado correctamente.
2025-05-04 17:01:15,379 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-04 17:01:15,381 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Verificando existencia de usuario...
2025-05-04 17:01:15,753 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] Login exitoso.
2025-05-04 17:01:15,755 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-04 17:01:15,757 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Proceso de login finalizado.
2025-05-04 17:01:15,758 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] ‚úÖ Test de login ejecutado correctamente.
2025-05-04 17:01:15,759 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] üß™ Test de login finalizado.
2025-05-04 17:01:15,762 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Iniciando generaci√≥n de token para correo 'carjisar@gmail.com'...
2025-05-04 17:01:15,764 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Link generado: http://localhost:5000/verificar/ImNhcmppc2FyQGdtYWlsLmNvbSI.aBfjqw.WQF6k1xYGVmQ4BN7OJJn_Nf4ttc
2025-05-04 17:01:21,051 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] Correo de verificaci√≥n enviado correctamente a 'carjisar@gmail.com'.
2025-05-04 17:01:21,051 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] ‚úÖ Test de env√≠o de correo ejecutado correctamente.
2025-05-04 17:01:21,058 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] üß™ Test de env√≠o de correo finalizado.
2025-05-04 17:01:21,061 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Iniciando generaci√≥n de token para correo 'carjisar@gmail.com'...
2025-05-04 17:01:21,066 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Link generado: http://localhost:5000/verificar/ImNhcmppc2FyQGdtYWlsLmNvbSI.aBfjsQ.o0-Ci0TqHfcbUhRf9n4bqROOnHA
2025-05-04 17:01:24,682 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] Correo de verificaci√≥n enviado correctamente a 'carjisar@gmail.com'.
2025-05-04 17:01:24,684 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Iniciando verificaci√≥n de token...
2025-05-04 17:01:24,704 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Token v√°lido para correo 'carjisar@gmail.com'. Procediendo a activar cuenta...
2025-05-04 17:01:25,367 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-04 17:01:25,370 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Iniciando actualizaci√≥n del usuario por 'd.email' = 'carjisar@gmail.com'...
2025-05-04 17:01:25,637 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Tabla 'detalle_usuarios' actualizada.
2025-05-04 17:01:25,721 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [GestionLogin.py] Usuario actualizado correctamente con ID 6.
2025-05-04 17:01:25,725 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-04 17:01:25,728 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Transacci√≥n de actualizaci√≥n finalizada.
2025-05-04 17:01:25,732 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] Cuenta verificada exitosamente.
2025-05-04 17:01:25,735 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] ‚úÖ Test de verificaci√≥n de cuenta ejecutado correctamente.
2025-05-04 17:01:25,737 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] üß™ Test de verificaci√≥n de cuenta finalizado.
2025-05-04 17:02:47,503 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-04 17:02:47,506 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Iniciando b√∫squeda del usuario por 'd.email' = 'carjisar@gmail.com'...
2025-05-04 17:02:47,667 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] Consulta completada para el id_usuario 'carjisar@gmail.com'.
2025-05-04 17:02:47,669 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-04 17:02:47,670 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Finalizaci√≥n de consulta de usuario.
2025-05-04 17:02:47,672 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] ‚úÖ Usuario consultado correctamente.
2025-05-04 17:03:46,551 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-04 17:03:46,552 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Iniciando lectura de usuarios y sus detalles...
2025-05-04 17:03:46,721 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] Se recuperaron 11 registros de usuarios con detalles.
2025-05-04 17:03:46,726 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-04 17:03:46,732 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Lectura de usuarios con detalles finalizada.
2025-05-04 17:03:46,750 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] ‚úÖ Usuarios le√≠dos correctamente.
2025-05-04 17:58:13,912 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-04 17:58:13,913 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Iniciando eliminaci√≥n del usuario por 'u.id_usuario' = '5'...
2025-05-04 17:58:14,270 - ERROR - Archivo: log.py - L√≠nea: 152 - [ERROR] [main_test.py] Error al eliminar usuario: permission denied for table detalle_usuarios

2025-05-04 17:58:14,272 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-04 17:58:14,274 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Transacci√≥n de eliminaci√≥n finalizada.
2025-05-04 17:58:14,276 - ERROR - Archivo: log.py - L√≠nea: 152 - [ERROR] [main_test.py] ‚ùå Error al eliminar usuario: 
2025-05-04 17:58:14,279 - ERROR - Archivo: log.py - L√≠nea: 152 - [ERROR] [<frozen runpy>] ‚ùå Error general al ejecutar manualmente: 
2025-05-04 18:05:13,292 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-04 18:05:13,293 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Iniciando actualizaci√≥n del usuario por 'd.email' = 'carjisar@gmail.com'...
2025-05-04 18:05:13,545 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Tabla 'detalle_usuarios' actualizada.
2025-05-04 18:05:13,630 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] Usuario actualizado correctamente con ID 7.
2025-05-04 18:05:13,634 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-04 18:05:13,637 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Transacci√≥n de actualizaci√≥n finalizada.
2025-05-04 18:05:13,638 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] ‚úÖ Usuario actualizado correctamente.
2025-05-04 18:05:14,261 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-04 18:05:14,263 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Iniciando b√∫squeda del usuario por 'd.email' = 'carjisar@gmail.com'...
2025-05-04 18:05:14,449 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] Consulta completada para el id_usuario 'carjisar@gmail.com'.
2025-05-04 18:05:14,451 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-04 18:05:14,452 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Finalizaci√≥n de consulta de usuario.
2025-05-04 18:05:14,453 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] ‚úÖ Usuario consultado correctamente.
2025-05-04 18:05:41,429 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-04 18:05:41,430 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Iniciando actualizaci√≥n del usuario por 'd.email' = 'carjisar@gmail.com'...
2025-05-04 18:05:41,672 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Tabla 'detalle_usuarios' actualizada.
2025-05-04 18:05:41,755 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] Usuario actualizado correctamente con ID 8.
2025-05-04 18:05:41,758 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-04 18:05:41,759 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Transacci√≥n de actualizaci√≥n finalizada.
2025-05-04 18:05:41,760 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] ‚úÖ Usuario actualizado correctamente.
2025-05-04 18:05:42,377 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-04 18:05:42,379 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Iniciando b√∫squeda del usuario por 'd.email' = 'carjisar@gmail.com'...
2025-05-04 18:05:42,545 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] Consulta completada para el id_usuario 'carjisar@gmail.com'.
2025-05-04 18:05:42,547 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-04 18:05:42,549 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Finalizaci√≥n de consulta de usuario.
2025-05-04 18:05:42,550 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] ‚úÖ Usuario consultado correctamente.
2025-05-04 18:09:40,131 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-04 18:09:40,132 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Iniciando actualizaci√≥n del usuario por 'd.email' = 'carjisar@gmail.com'...
2025-05-04 18:09:40,376 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Tabla 'detalle_usuarios' actualizada.
2025-05-04 18:09:40,462 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] Usuario actualizado correctamente con ID 9.
2025-05-04 18:09:40,466 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-04 18:09:40,468 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Transacci√≥n de actualizaci√≥n finalizada.
2025-05-04 18:09:40,471 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] ‚úÖ Usuario actualizado correctamente.
2025-05-04 18:09:41,058 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-04 18:09:41,060 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Iniciando b√∫squeda del usuario por 'u.id_usuario' = '4'...
2025-05-04 18:09:41,223 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] Consulta completada para el id_usuario '4'.
2025-05-04 18:09:41,224 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-04 18:09:41,225 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Finalizaci√≥n de consulta de usuario.
2025-05-04 18:09:41,227 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] ‚úÖ Usuario consultado correctamente.
2025-05-04 18:09:57,277 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-04 18:09:57,278 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Iniciando actualizaci√≥n del usuario por 'u.id_usuario' = '4'...
2025-05-04 18:09:57,533 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Tabla 'detalle_usuarios' actualizada.
2025-05-04 18:09:57,620 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] Usuario actualizado correctamente con ID 4.
2025-05-04 18:09:57,622 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-04 18:09:57,624 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Transacci√≥n de actualizaci√≥n finalizada.
2025-05-04 18:09:57,626 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] ‚úÖ Usuario actualizado correctamente.
2025-05-04 18:09:58,214 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-04 18:09:58,218 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Iniciando b√∫squeda del usuario por 'u.id_usuario' = '4'...
2025-05-04 18:09:58,384 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] Consulta completada para el id_usuario '4'.
2025-05-04 18:09:58,386 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-04 18:09:58,386 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Finalizaci√≥n de consulta de usuario.
2025-05-04 18:09:58,388 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] ‚úÖ Usuario consultado correctamente.
2025-05-04 18:18:36,339 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-04 18:18:36,339 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Iniciando lectura de usuarios y sus detalles...
2025-05-04 18:18:36,524 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] Se recuperaron 12 registros de usuarios con detalles.
2025-05-04 18:18:36,528 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-04 18:18:36,528 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Lectura de usuarios con detalles finalizada.
2025-05-04 18:18:36,533 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] ‚úÖ Usuarios le√≠dos correctamente.
2025-05-04 18:43:40,724 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-04 18:43:40,726 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Iniciando lectura de usuarios y sus detalles...
2025-05-04 18:43:40,897 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] Se recuperaron 12 registros de usuarios con detalles.
2025-05-04 18:43:40,900 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-04 18:43:40,903 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Lectura de usuarios con detalles finalizada.
2025-05-04 18:43:40,905 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] ‚úÖ Usuarios le√≠dos correctamente.
2025-05-04 18:44:32,722 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-04 18:44:32,723 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Iniciando eliminaci√≥n del usuario por 'u.id_usuario' = '9'...
2025-05-04 18:44:32,969 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Detalle del usuario eliminado.
2025-05-04 18:44:33,135 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] Usuario con ID 9 eliminado correctamente.
2025-05-04 18:44:33,138 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-04 18:44:33,141 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Transacci√≥n de eliminaci√≥n finalizada.
2025-05-04 18:44:33,147 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] ‚úÖ Usuario eliminado correctamente.
2025-05-04 18:44:33,815 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-04 18:44:33,825 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Iniciando lectura de usuarios y sus detalles...
2025-05-04 18:44:34,003 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] Se recuperaron 11 registros de usuarios con detalles.
2025-05-04 18:44:34,005 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-04 18:44:34,005 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Lectura de usuarios con detalles finalizada.
2025-05-04 18:44:34,005 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] ‚úÖ Usuarios le√≠dos correctamente.
2025-05-04 18:45:32,806 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-04 18:45:32,808 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Iniciando eliminaci√≥n del usuario por 'u.id_usuario' = '8'...
2025-05-04 18:45:33,057 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Detalle del usuario eliminado.
2025-05-04 18:45:33,223 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] Usuario con ID 8 eliminado correctamente.
2025-05-04 18:45:33,225 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-04 18:45:33,228 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Transacci√≥n de eliminaci√≥n finalizada.
2025-05-04 18:45:33,229 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] ‚úÖ Usuario eliminado correctamente.
2025-05-04 18:45:33,894 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-04 18:45:33,897 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Iniciando lectura de usuarios y sus detalles...
2025-05-04 18:45:34,078 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] Se recuperaron 13 registros de usuarios con detalles.
2025-05-04 18:45:34,081 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-04 18:45:34,083 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Lectura de usuarios con detalles finalizada.
2025-05-04 18:45:34,085 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] ‚úÖ Usuarios le√≠dos correctamente.
2025-05-04 18:45:41,907 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-04 18:45:41,909 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Iniciando eliminaci√≥n del usuario por 'u.id_usuario' = '7'...
2025-05-04 18:45:42,166 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Detalle del usuario eliminado.
2025-05-04 18:45:42,340 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] Usuario con ID 7 eliminado correctamente.
2025-05-04 18:45:42,344 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-04 18:45:42,348 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Transacci√≥n de eliminaci√≥n finalizada.
2025-05-04 18:45:42,350 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] ‚úÖ Usuario eliminado correctamente.
2025-05-04 18:45:42,949 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-04 18:45:42,951 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Iniciando lectura de usuarios y sus detalles...
2025-05-04 18:45:43,117 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] Se recuperaron 12 registros de usuarios con detalles.
2025-05-04 18:45:43,123 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-04 18:45:43,125 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Lectura de usuarios con detalles finalizada.
2025-05-04 18:45:43,127 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] ‚úÖ Usuarios le√≠dos correctamente.
2025-05-04 18:45:53,040 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-04 18:45:53,041 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Iniciando eliminaci√≥n del usuario por 'u.id_usuario' = '6'...
2025-05-04 18:45:53,310 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Detalle del usuario eliminado.
2025-05-04 18:45:53,490 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] Usuario con ID 6 eliminado correctamente.
2025-05-04 18:45:53,493 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-04 18:45:53,494 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Transacci√≥n de eliminaci√≥n finalizada.
2025-05-04 18:45:53,498 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] ‚úÖ Usuario eliminado correctamente.
2025-05-04 18:45:54,159 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-04 18:45:54,163 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Iniciando lectura de usuarios y sus detalles...
2025-05-04 18:45:54,340 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] Se recuperaron 11 registros de usuarios con detalles.
2025-05-04 18:45:54,344 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-04 18:45:54,345 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Lectura de usuarios con detalles finalizada.
2025-05-04 18:45:54,346 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] ‚úÖ Usuarios le√≠dos correctamente.
2025-05-04 18:46:16,158 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-04 18:46:16,160 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Iniciando eliminaci√≥n del usuario por 'u.id_usuario' = '5'...
2025-05-04 18:46:16,429 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Detalle del usuario eliminado.
2025-05-04 18:46:16,606 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] Usuario con ID 5 eliminado correctamente.
2025-05-04 18:46:16,607 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-04 18:46:16,612 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Transacci√≥n de eliminaci√≥n finalizada.
2025-05-04 18:46:16,614 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] ‚úÖ Usuario eliminado correctamente.
2025-05-04 18:46:17,210 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-04 18:46:17,211 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Iniciando lectura de usuarios y sus detalles...
2025-05-04 18:46:17,376 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] Se recuperaron 10 registros de usuarios con detalles.
2025-05-04 18:46:17,377 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-04 18:46:17,378 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Lectura de usuarios con detalles finalizada.
2025-05-04 18:46:17,381 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] ‚úÖ Usuarios le√≠dos correctamente.
2025-05-04 18:47:28,065 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-04 18:47:28,068 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Iniciando b√∫squeda del usuario por 'u.id_usuario' = '5'...
2025-05-04 18:47:28,233 - WARNING - Archivo: log.py - L√≠nea: 139 - [WARNING] [main_test.py] No se encontr√≥ usuario con el id_usuario '5'.
2025-05-04 18:47:28,238 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-04 18:47:28,240 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Finalizaci√≥n de consulta de usuario.
2025-05-04 18:47:28,244 - ERROR - Archivo: log.py - L√≠nea: 152 - [ERROR] [main_test.py] ‚ùå Error al consultar usuario: 
2025-05-04 18:47:28,245 - ERROR - Archivo: log.py - L√≠nea: 152 - [ERROR] [<frozen runpy>] ‚ùå Error general al ejecutar manualmente: 
2025-05-05 00:18:56,374 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-05 00:18:56,552 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] üß© Se encontraron 2 tablas.
2025-05-05 00:18:56,555 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] 
üìÑ Tabla: public.detalle_usuarios
2025-05-05 00:18:56,646 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py]     - id_detalle_usuarios (integer, NULLABLE: NO)
2025-05-05 00:18:56,650 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py]     - id_usuario (integer, NULLABLE: NO)
2025-05-05 00:18:56,653 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py]     - contrasena (text, NULLABLE: NO)
2025-05-05 00:18:56,656 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py]     - token (text, NULLABLE: YES)
2025-05-05 00:18:56,662 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py]     - grupo (integer, NULLABLE: NO)
2025-05-05 00:18:56,668 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py]     - email (character varying, NULLABLE: NO)
2025-05-05 00:18:56,676 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py]     - estado_cuenta (boolean, NULLABLE: NO)
2025-05-05 00:18:56,776 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py]     üîë PRIMARY KEY: id_detalle_usuarios
2025-05-05 00:18:56,868 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] 
üìÑ Tabla: public.usuarios
2025-05-05 00:18:56,956 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py]     - id_usuario (integer, NULLABLE: NO)
2025-05-05 00:18:56,960 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py]     - nick_name (character varying, NULLABLE: NO)
2025-05-05 00:18:56,962 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py]     - fecha (date, NULLABLE: NO)
2025-05-05 00:18:56,964 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py]     - nombre (character varying, NULLABLE: YES)
2025-05-05 00:18:57,055 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py]     üîë PRIMARY KEY: id_usuario
2025-05-05 00:18:57,143 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] ‚úÖ Exploraci√≥n de estructura completada.
2025-05-05 00:18:57,148 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-05 00:18:57,151 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] üß™ Test de exploraci√≥n finalizado.
2025-05-05 00:28:51,136 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-05 00:28:51,138 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Iniciando inserci√≥n de nuevo usuario y detalle...
2025-05-05 00:28:51,372 - ERROR - Archivo: log.py - L√≠nea: 152 - [ERROR] [main_test.py] Error general al crear usuario: 'nombre'
2025-05-05 00:28:51,374 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-05 00:28:51,374 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Transacci√≥n de creaci√≥n de usuario finalizada.
2025-05-05 00:28:51,376 - ERROR - Archivo: log.py - L√≠nea: 152 - [ERROR] [main_test.py] ‚ùå Error al crear usuario: 
2025-05-05 00:28:51,376 - ERROR - Archivo: log.py - L√≠nea: 152 - [ERROR] [<frozen runpy>] ‚ùå Error general al ejecutar manualmente: 
2025-05-05 00:36:19,987 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-05 00:36:19,987 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Iniciando inserci√≥n de nuevo usuario y detalle...
2025-05-05 00:36:20,216 - ERROR - Archivo: log.py - L√≠nea: 152 - [ERROR] [main_test.py] Error general al crear usuario: not all arguments converted during string formatting
2025-05-05 00:36:20,217 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-05 00:36:20,228 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Transacci√≥n de creaci√≥n de usuario finalizada.
2025-05-05 00:36:20,232 - ERROR - Archivo: log.py - L√≠nea: 152 - [ERROR] [main_test.py] ‚ùå Error al crear usuario: 
2025-05-05 00:36:20,237 - ERROR - Archivo: log.py - L√≠nea: 152 - [ERROR] [<frozen runpy>] ‚ùå Error general al ejecutar manualmente: 
2025-05-05 00:38:45,785 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-05 00:38:45,787 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Iniciando inserci√≥n de nuevo usuario y detalle...
2025-05-05 00:38:46,178 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Usuario creado con ID: 23
2025-05-05 00:38:46,348 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] Usuario y detalle insertados correctamente.
2025-05-05 00:38:46,361 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-05 00:38:46,364 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Transacci√≥n de creaci√≥n de usuario finalizada.
2025-05-05 00:38:46,370 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] ‚úÖ Usuario creado correctamente.
2025-05-05 00:38:46,990 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-05 00:38:46,990 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Iniciando actualizaci√≥n del usuario por 'd.email' = 'carjisar@gmail.com'...
2025-05-05 00:38:47,244 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] Usuario actualizado correctamente con ID 4.
2025-05-05 00:38:47,247 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-05 00:38:47,266 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Transacci√≥n de actualizaci√≥n finalizada.
2025-05-05 00:38:47,278 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-05 00:38:47,280 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Transacci√≥n de eliminaci√≥n finalizada.
2025-05-05 00:38:47,286 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] ‚úÖ Usuario actualizado correctamente.
2025-05-05 00:38:47,909 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-05 00:38:47,917 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Iniciando b√∫squeda del usuario por 'u.id_usuario' = '4'...
2025-05-05 00:38:48,085 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] Consulta completada para el id_usuario '4'.
2025-05-05 00:38:48,087 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-05 00:38:48,087 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Finalizaci√≥n de consulta de usuario.
2025-05-05 00:38:48,087 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] ‚úÖ Usuario consultado correctamente.
2025-05-05 00:38:48,761 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-05 00:38:48,766 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Iniciando lectura de usuarios y sus detalles...
2025-05-05 00:38:48,947 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] Se recuperaron 14 registros de usuarios con detalles.
2025-05-05 00:38:48,950 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-05 00:38:48,950 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Lectura de usuarios con detalles finalizada.
2025-05-05 00:38:48,954 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] ‚úÖ Usuarios le√≠dos correctamente.
2025-05-05 00:41:27,319 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-05 00:41:27,319 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Iniciando actualizaci√≥n del usuario por 'd.email' = 'carjisar@gmail.com'...
2025-05-05 00:41:27,577 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] Usuario actualizado correctamente con ID 4.
2025-05-05 00:41:27,582 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-05 00:41:27,582 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Transacci√≥n de actualizaci√≥n finalizada.
2025-05-05 00:41:27,587 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-05 00:41:27,591 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Transacci√≥n de eliminaci√≥n finalizada.
2025-05-05 00:41:27,595 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] ‚úÖ Usuario actualizado correctamente.
2025-05-05 00:41:28,220 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-05 00:41:28,220 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Iniciando b√∫squeda del usuario por 'u.id_usuario' = '4'...
2025-05-05 00:41:28,398 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] Consulta completada para el id_usuario '4'.
2025-05-05 00:41:28,401 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-05 00:41:28,403 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Finalizaci√≥n de consulta de usuario.
2025-05-05 00:41:28,403 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] ‚úÖ Usuario consultado correctamente.
2025-05-05 00:41:29,019 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-05 00:41:29,021 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Iniciando lectura de usuarios y sus detalles...
2025-05-05 00:41:29,194 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] Se recuperaron 14 registros de usuarios con detalles.
2025-05-05 00:41:29,194 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-05 00:41:29,197 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Lectura de usuarios con detalles finalizada.
2025-05-05 00:41:29,198 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] ‚úÖ Usuarios le√≠dos correctamente.
2025-05-05 00:44:56,345 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-05 00:44:56,345 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Iniciando actualizaci√≥n del usuario por 'd.email' = 'carjisar@gmail.com'...
2025-05-05 00:44:56,612 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Tabla 'usuarios' actualizada.
2025-05-05 00:44:56,704 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] Usuario actualizado correctamente con ID 4.
2025-05-05 00:44:56,707 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-05 00:44:56,709 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Transacci√≥n de actualizaci√≥n finalizada.
2025-05-05 00:44:56,711 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-05 00:44:56,712 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Transacci√≥n de eliminaci√≥n finalizada.
2025-05-05 00:44:56,714 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] ‚úÖ Usuario actualizado correctamente.
2025-05-05 00:44:57,349 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-05 00:44:57,358 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Iniciando b√∫squeda del usuario por 'u.id_usuario' = '4'...
2025-05-05 00:44:57,527 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] Consulta completada para el id_usuario '4'.
2025-05-05 00:44:57,527 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-05 00:44:57,536 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Finalizaci√≥n de consulta de usuario.
2025-05-05 00:44:57,541 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] ‚úÖ Usuario consultado correctamente.
2025-05-05 00:44:58,181 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-05 00:44:58,181 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Iniciando lectura de usuarios y sus detalles...
2025-05-05 00:44:58,357 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] Se recuperaron 14 registros de usuarios con detalles.
2025-05-05 00:44:58,357 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-05 00:44:58,357 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Lectura de usuarios con detalles finalizada.
2025-05-05 00:44:58,357 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] ‚úÖ Usuarios le√≠dos correctamente.
2025-05-05 00:45:53,063 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-05 00:45:53,063 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Iniciando actualizaci√≥n del usuario por 'd.email' = 'carjisar@gmail.com'...
2025-05-05 00:45:53,317 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Tabla 'usuarios' actualizada.
2025-05-05 00:45:53,407 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] Usuario actualizado correctamente con ID 4.
2025-05-05 00:45:53,410 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-05 00:45:53,429 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Transacci√≥n de actualizaci√≥n finalizada.
2025-05-05 00:45:53,436 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-05 00:45:53,438 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Transacci√≥n de eliminaci√≥n finalizada.
2025-05-05 00:45:53,442 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] ‚úÖ Usuario actualizado correctamente.
2025-05-05 00:45:54,047 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-05 00:45:54,057 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Iniciando b√∫squeda del usuario por 'u.id_usuario' = '4'...
2025-05-05 00:45:54,227 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] Consulta completada para el id_usuario '4'.
2025-05-05 00:45:54,227 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-05 00:45:54,227 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Finalizaci√≥n de consulta de usuario.
2025-05-05 00:45:54,227 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] ‚úÖ Usuario consultado correctamente.
2025-05-05 00:45:54,870 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-05 00:45:54,870 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Iniciando eliminaci√≥n del usuario por 'u.id_usuario' = '23'...
2025-05-05 00:45:55,127 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Detalle del usuario eliminado.
2025-05-05 00:45:55,299 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] Usuario con ID 23 eliminado correctamente.
2025-05-05 00:45:55,299 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-05 00:45:55,299 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Transacci√≥n de eliminaci√≥n finalizada.
2025-05-05 00:45:55,299 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] ‚úÖ Usuario eliminado correctamente.
2025-05-05 00:45:55,938 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-05 00:45:55,939 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Iniciando lectura de usuarios y sus detalles...
2025-05-05 00:45:56,109 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] Se recuperaron 13 registros de usuarios con detalles.
2025-05-05 00:45:56,111 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-05 00:45:56,112 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Lectura de usuarios con detalles finalizada.
2025-05-05 00:45:56,115 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] ‚úÖ Usuarios le√≠dos correctamente.
2025-05-05 00:50:12,591 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-05 00:50:12,597 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Iniciando b√∫squeda del usuario por 'u.id_usuario' = '23'...
2025-05-05 00:50:12,774 - WARNING - Archivo: log.py - L√≠nea: 139 - [WARNING] [main_test.py] No se encontr√≥ usuario con el id_usuario '23'.
2025-05-05 00:50:12,777 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-05 00:50:12,779 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Finalizaci√≥n de consulta de usuario.
2025-05-05 00:50:12,784 - ERROR - Archivo: log.py - L√≠nea: 152 - [ERROR] [main_test.py] ‚ùå Error al consultar usuario: 
2025-05-05 00:50:12,785 - ERROR - Archivo: log.py - L√≠nea: 152 - [ERROR] [<frozen runpy>] ‚ùå Error general al ejecutar manualmente: 
2025-05-06 21:04:17,353 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-06 21:04:17,353 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Iniciando actualizaci√≥n del usuario por 'd.email' = 'carjisar@gmail.com'...
2025-05-06 21:04:17,823 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Tabla 'detalle_usuarios' actualizada.
2025-05-06 21:04:17,909 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] Usuario actualizado correctamente con ID 4.
2025-05-06 21:04:17,934 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-06 21:04:17,937 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Transacci√≥n de actualizaci√≥n finalizada.
2025-05-06 21:04:17,940 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-06 21:04:17,940 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Transacci√≥n de eliminaci√≥n finalizada.
2025-05-06 21:04:17,943 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] ‚úÖ Usuario actualizado correctamente.
2025-05-06 21:04:18,563 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-06 21:04:18,568 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Iniciando b√∫squeda del usuario por 'u.id_usuario' = '23'...
2025-05-06 21:04:18,739 - WARNING - Archivo: log.py - L√≠nea: 139 - [WARNING] [main_test.py] No se encontr√≥ usuario con el id_usuario '23'.
2025-05-06 21:04:18,739 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-06 21:04:18,739 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Finalizaci√≥n de consulta de usuario.
2025-05-06 21:04:18,744 - ERROR - Archivo: log.py - L√≠nea: 152 - [ERROR] [main_test.py] ‚ùå Error al consultar usuario: 
2025-05-06 21:04:18,744 - ERROR - Archivo: log.py - L√≠nea: 152 - [ERROR] [<frozen runpy>] ‚ùå Error general al ejecutar manualmente: 
2025-05-06 21:04:36,001 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-06 21:04:36,001 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Iniciando actualizaci√≥n del usuario por 'd.email' = 'carjisar@gmail.com'...
2025-05-06 21:04:36,469 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Tabla 'detalle_usuarios' actualizada.
2025-05-06 21:04:36,559 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] Usuario actualizado correctamente con ID 4.
2025-05-06 21:04:36,561 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-06 21:04:36,565 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Transacci√≥n de actualizaci√≥n finalizada.
2025-05-06 21:04:36,566 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-06 21:04:36,567 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Transacci√≥n de eliminaci√≥n finalizada.
2025-05-06 21:04:36,569 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] ‚úÖ Usuario actualizado correctamente.
2025-05-06 21:04:37,184 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-06 21:04:37,189 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Iniciando b√∫squeda del usuario por 'u.id_usuario' = '4'...
2025-05-06 21:04:37,359 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] Consulta completada para el id_usuario '4'.
2025-05-06 21:04:37,359 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-06 21:04:37,363 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Finalizaci√≥n de consulta de usuario.
2025-05-06 21:04:37,368 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] ‚úÖ Usuario consultado correctamente.
2025-05-06 22:04:57,711 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-06 22:04:57,717 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [app.py] Verificando existencia de usuario...
2025-05-06 22:04:57,897 - ERROR - Archivo: log.py - L√≠nea: 152 - [ERROR] [app.py] Usuario no encontrado.
2025-05-06 22:04:57,972 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-06 22:04:58,015 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [app.py] Proceso de login finalizado.
2025-05-06 22:05:08,046 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-06 22:05:08,055 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [app.py] Verificando existencia de usuario...
2025-05-06 22:05:08,223 - ERROR - Archivo: log.py - L√≠nea: 152 - [ERROR] [app.py] Usuario no encontrado.
2025-05-06 22:05:08,228 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-06 22:05:08,245 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [app.py] Proceso de login finalizado.
2025-05-06 22:05:17,351 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-06 22:05:17,355 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [app.py] Verificando existencia de usuario...
2025-05-06 22:05:18,071 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [app.py] Login exitoso.
2025-05-06 22:05:18,084 - ERROR - Archivo: log.py - L√≠nea: 152 - [ERROR] [app.py] Error en login: The session is unavailable because no secret key was set.  Set the secret_key on the application to something unique and secret.
2025-05-06 22:05:18,107 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-06 22:05:18,126 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [app.py] Proceso de login finalizado.
2025-05-06 22:07:11,304 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-06 22:07:11,306 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [app.py] Verificando existencia de usuario...
2025-05-06 22:07:11,707 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [app.py] Login exitoso.
2025-05-06 22:07:11,708 - ERROR - Archivo: log.py - L√≠nea: 152 - [ERROR] [app.py] Error en login: The session is unavailable because no secret key was set.  Set the secret_key on the application to something unique and secret.
2025-05-06 22:07:11,709 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-06 22:07:11,711 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [app.py] Proceso de login finalizado.
2025-05-06 22:07:24,972 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-06 22:07:24,976 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [app.py] Verificando existencia de usuario...
2025-05-06 22:07:25,153 - ERROR - Archivo: log.py - L√≠nea: 152 - [ERROR] [app.py] Usuario no encontrado.
2025-05-06 22:07:25,162 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-06 22:07:25,181 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [app.py] Proceso de login finalizado.
2025-05-06 22:07:37,810 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-06 22:07:37,815 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [app.py] Verificando existencia de usuario...
2025-05-06 22:07:38,516 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [app.py] Login exitoso.
2025-05-06 22:07:38,523 - ERROR - Archivo: log.py - L√≠nea: 152 - [ERROR] [app.py] Error en login: The session is unavailable because no secret key was set.  Set the secret_key on the application to something unique and secret.
2025-05-06 22:07:38,528 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-06 22:07:38,532 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [app.py] Proceso de login finalizado.
2025-05-06 22:09:22,681 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-06 22:09:22,682 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [app.py] Verificando existencia de usuario...
2025-05-06 22:09:23,094 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [app.py] Login exitoso.
2025-05-06 22:09:23,096 - ERROR - Archivo: log.py - L√≠nea: 152 - [ERROR] [app.py] Error en login: The session is unavailable because no secret key was set.  Set the secret_key on the application to something unique and secret.
2025-05-06 22:09:23,099 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-06 22:09:23,100 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [app.py] Proceso de login finalizado.
2025-05-06 22:12:06,342 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-06 22:12:06,349 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [app.py] Verificando existencia de usuario...
2025-05-06 22:12:07,229 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [app.py] Login exitoso.
2025-05-06 22:12:07,251 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-06 22:12:07,262 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [app.py] Proceso de login finalizado.
2025-05-06 22:13:11,023 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-06 22:13:11,024 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [app.py] Verificando existencia de usuario...
2025-05-06 22:13:11,496 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [app.py] Login exitoso.
2025-05-06 22:13:11,498 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-06 22:13:11,500 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [app.py] Proceso de login finalizado.
2025-05-06 22:14:08,957 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-06 22:14:08,958 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [app.py] Verificando existencia de usuario...
2025-05-06 22:14:09,346 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [app.py] Login exitoso.
2025-05-06 22:14:09,348 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-06 22:14:09,350 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [app.py] Proceso de login finalizado.
2025-05-06 22:14:28,642 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-06 22:14:28,644 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [app.py] Verificando existencia de usuario...
2025-05-06 22:14:29,073 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [app.py] Login exitoso.
2025-05-06 22:14:29,075 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-06 22:14:29,076 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [app.py] Proceso de login finalizado.
2025-05-07 00:18:56,374 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-07 00:18:56,374 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Verificando existencia de usuario...
2025-05-07 00:18:56,964 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main.py] Login exitoso.
2025-05-07 00:18:56,968 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-07 00:18:56,975 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Proceso de login finalizado.
2025-05-07 00:28:50,901 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main.py] Sesi√≥n cerrada correctamente.
2025-05-07 00:29:03,301 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-07 00:29:03,308 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Verificando existencia de usuario...
2025-05-07 00:29:03,968 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main.py] Login exitoso.
2025-05-07 00:29:03,973 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-07 00:29:03,977 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Proceso de login finalizado.
2025-05-07 00:29:08,290 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main.py] Sesi√≥n cerrada correctamente.
2025-05-07 00:30:28,818 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-07 00:30:28,818 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Verificando existencia de usuario...
2025-05-07 00:30:29,255 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main.py] Login exitoso.
2025-05-07 00:30:29,260 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-07 00:30:29,263 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Proceso de login finalizado.
2025-05-07 00:30:30,294 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main.py] Sesi√≥n cerrada correctamente.
2025-05-07 00:34:37,827 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-07 00:34:37,837 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Verificando existencia de usuario...
2025-05-07 00:34:38,568 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main.py] Login exitoso.
2025-05-07 00:34:38,576 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-07 00:34:38,587 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Proceso de login finalizado.
2025-05-07 00:34:40,513 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main.py] Sesi√≥n cerrada correctamente.
2025-05-07 00:35:01,545 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-07 00:35:01,546 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Verificando existencia de usuario...
2025-05-07 00:35:01,983 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main.py] Login exitoso.
2025-05-07 00:35:01,987 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-07 00:35:01,989 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Proceso de login finalizado.
2025-05-07 00:35:03,533 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main.py] Sesi√≥n cerrada correctamente.
2025-05-07 00:36:23,397 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-07 00:36:23,405 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Verificando existencia de usuario...
2025-05-07 00:36:24,075 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main.py] Login exitoso.
2025-05-07 00:36:24,079 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-07 00:36:24,084 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Proceso de login finalizado.
2025-05-07 00:37:34,965 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main.py] Sesi√≥n cerrada correctamente.
2025-05-07 00:38:01,438 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-07 00:38:01,444 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Verificando existencia de usuario...
2025-05-07 00:38:01,937 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main.py] Login exitoso.
2025-05-07 00:38:01,946 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-07 00:38:01,949 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Proceso de login finalizado.
2025-05-07 00:38:04,314 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main.py] Sesi√≥n cerrada correctamente.
2025-05-07 00:38:27,141 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-07 00:38:27,144 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Verificando existencia de usuario...
2025-05-07 00:38:27,718 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main.py] Login exitoso.
2025-05-07 00:38:27,724 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-07 00:38:27,728 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Proceso de login finalizado.
2025-05-07 00:38:35,428 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main.py] Sesi√≥n cerrada correctamente.
2025-05-07 00:53:07,469 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-07 00:53:07,475 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Iniciando inserci√≥n de nuevo usuario y detalle...
2025-05-07 00:53:08,119 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Usuario creado con ID: 42
2025-05-07 00:53:08,295 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main.py] Usuario y detalle insertados correctamente.
2025-05-07 00:53:08,298 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-07 00:53:08,301 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Transacci√≥n de creaci√≥n de usuario finalizada.
2025-05-07 00:53:35,159 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-07 00:53:35,164 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Verificando existencia de usuario...
2025-05-07 00:53:35,721 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main.py] Login exitoso.
2025-05-07 00:53:35,726 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-07 00:53:35,732 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Proceso de login finalizado.
2025-05-07 00:56:16,921 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-07 00:56:16,923 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Verificando existencia de usuario...
2025-05-07 00:56:17,325 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main.py] Login exitoso.
2025-05-07 00:56:17,328 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-07 00:56:17,328 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Proceso de login finalizado.
2025-05-07 01:01:24,047 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-07 01:01:24,049 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Verificando existencia de usuario...
2025-05-07 01:01:24,456 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main.py] Login exitoso.
2025-05-07 01:01:24,458 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-07 01:01:24,460 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Proceso de login finalizado.
2025-05-07 01:16:31,914 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-07 01:16:31,915 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Verificando existencia de usuario...
2025-05-07 01:16:32,316 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main.py] Login exitoso.
2025-05-07 01:16:32,318 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-07 01:16:32,319 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Proceso de login finalizado.
2025-05-07 01:18:22,322 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-07 01:18:22,326 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Verificando existencia de usuario...
2025-05-07 01:18:22,917 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main.py] Login exitoso.
2025-05-07 01:18:22,926 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-07 01:18:22,936 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Proceso de login finalizado.
2025-05-07 01:24:13,235 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-07 01:24:13,239 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Verificando existencia de usuario...
2025-05-07 01:24:13,883 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main.py] Login exitoso.
2025-05-07 01:24:13,890 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-07 01:24:13,901 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Proceso de login finalizado.
2025-05-07 01:24:15,794 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Iniciando generaci√≥n de token para correo 'carlos1006744921@gmail.com'...
2025-05-07 01:24:15,799 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Link generado: http://localhost:5000/verificar/ImNhcmxvczEwMDY3NDQ5MjFAZ21haWwuY29tIg.aBr8jw.v_YdbIgIDKcNoviigWAbnI1ILKQ
2025-05-07 01:24:20,050 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main.py] Correo de verificaci√≥n enviado correctamente a 'carlos1006744921@gmail.com'.
2025-05-07 01:27:36,911 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-07 01:27:36,912 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Verificando existencia de usuario...
2025-05-07 01:27:37,312 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main.py] Login exitoso.
2025-05-07 01:27:37,322 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-07 01:27:37,339 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Proceso de login finalizado.
2025-05-07 01:27:41,033 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Iniciando generaci√≥n de token para correo 'carlos1006744921@gmail.com'...
2025-05-07 01:27:41,037 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Link generado: http://localhost:5000/login/verificar/ImNhcmxvczEwMDY3NDQ5MjFAZ21haWwuY29tIg.aBr9XQ.zUpxVKFYNwmQFJ_633oPUhuptDE
2025-05-07 01:27:44,989 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main.py] Correo de verificaci√≥n enviado correctamente a 'carlos1006744921@gmail.com'.
2025-05-07 01:28:05,562 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Iniciando verificaci√≥n de token...
2025-05-07 01:28:05,565 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Token v√°lido para correo 'carlos1006744921@gmail.com'. Procediendo a activar cuenta...
2025-05-07 01:28:06,243 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-07 01:28:06,255 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Iniciando actualizaci√≥n del usuario por 'd.email' = 'carlos1006744921@gmail.com'...
2025-05-07 01:28:06,529 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Tabla 'detalle_usuarios' actualizada.
2025-05-07 01:28:06,624 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [GestionLogin.py] Usuario actualizado correctamente con ID 42.
2025-05-07 01:28:06,633 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-07 01:28:06,671 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Transacci√≥n de actualizaci√≥n finalizada.
2025-05-07 01:28:06,703 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-07 01:28:06,716 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Transacci√≥n de eliminaci√≥n finalizada.
2025-05-07 01:28:06,748 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main.py] Cuenta verificada exitosamente.
2025-05-07 01:29:04,006 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Iniciando verificaci√≥n de token...
2025-05-07 01:29:04,008 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Token v√°lido para correo 'carlos1006744921@gmail.com'. Procediendo a activar cuenta...
2025-05-07 01:29:04,654 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-07 01:29:04,655 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Iniciando actualizaci√≥n del usuario por 'd.email' = 'carlos1006744921@gmail.com'...
2025-05-07 01:29:04,899 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Tabla 'detalle_usuarios' actualizada.
2025-05-07 01:29:04,988 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [GestionLogin.py] Usuario actualizado correctamente con ID 42.
2025-05-07 01:29:04,996 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-07 01:29:05,001 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Transacci√≥n de actualizaci√≥n finalizada.
2025-05-07 01:29:05,002 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-07 01:29:05,004 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Transacci√≥n de eliminaci√≥n finalizada.
2025-05-07 01:29:05,005 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main.py] Cuenta verificada exitosamente.
2025-05-07 01:29:26,237 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-07 01:29:26,242 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Verificando existencia de usuario...
2025-05-07 01:29:26,811 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main.py] Login exitoso.
2025-05-07 01:29:26,818 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-07 01:29:26,825 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Proceso de login finalizado.
2025-05-07 01:33:30,278 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-07 01:33:30,278 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Iniciando actualizaci√≥n del usuario por 'd.email' = 'carlos1006744921@gmail.com'...
2025-05-07 01:33:30,782 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Tabla 'detalle_usuarios' actualizada.
2025-05-07 01:33:30,866 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] Usuario actualizado correctamente con ID 42.
2025-05-07 01:33:30,866 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-07 01:33:30,869 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Transacci√≥n de actualizaci√≥n finalizada.
2025-05-07 01:33:30,870 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-07 01:33:30,870 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Transacci√≥n de eliminaci√≥n finalizada.
2025-05-07 01:33:30,872 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] ‚úÖ Usuario actualizado correctamente.
2025-05-07 01:33:31,524 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-07 01:33:31,526 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Iniciando b√∫squeda del usuario por 'u.id_usuario' = '4'...
2025-05-07 01:33:31,703 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] Consulta completada para el id_usuario '4'.
2025-05-07 01:33:31,706 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-07 01:33:31,708 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Finalizaci√≥n de consulta de usuario.
2025-05-07 01:33:31,708 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] ‚úÖ Usuario consultado correctamente.
2025-05-07 01:33:43,581 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-07 01:33:43,584 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Verificando existencia de usuario...
2025-05-07 01:33:44,026 - ERROR - Archivo: log.py - L√≠nea: 152 - [ERROR] [main.py] Contrase√±a incorrecta.
2025-05-07 01:33:44,028 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-07 01:33:44,028 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Proceso de login finalizado.
2025-05-07 01:33:48,483 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-07 01:33:48,486 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Verificando existencia de usuario...
2025-05-07 01:33:49,084 - ERROR - Archivo: log.py - L√≠nea: 152 - [ERROR] [main.py] Contrase√±a incorrecta.
2025-05-07 01:33:49,089 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-07 01:33:49,100 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Proceso de login finalizado.
2025-05-07 01:33:50,979 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-07 01:33:50,982 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Verificando existencia de usuario...
2025-05-07 01:33:51,518 - ERROR - Archivo: log.py - L√≠nea: 152 - [ERROR] [main.py] Contrase√±a incorrecta.
2025-05-07 01:33:51,521 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-07 01:33:51,525 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Proceso de login finalizado.
2025-05-07 01:34:02,111 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-07 01:34:02,117 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Verificando existencia de usuario...
2025-05-07 01:34:02,765 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main.py] Login exitoso.
2025-05-07 01:34:02,811 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-07 01:34:02,836 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Proceso de login finalizado.
2025-05-07 01:34:05,849 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Iniciando generaci√≥n de token para correo 'carlos1006744921@gmail.com'...
2025-05-07 01:34:05,854 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Link generado: http://localhost:5000/login/verificar/ImNhcmxvczEwMDY3NDQ5MjFAZ21haWwuY29tIg.aBr-3Q.6PEWXd_FWUreOkgzxup7SppneBs
2025-05-07 01:34:10,626 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main.py] Correo de verificaci√≥n enviado correctamente a 'carlos1006744921@gmail.com'.
2025-05-07 01:35:27,741 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Iniciando verificaci√≥n de token...
2025-05-07 01:35:27,747 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Token v√°lido para correo 'carlos1006744921@gmail.com'. Procediendo a activar cuenta...
2025-05-07 01:35:29,407 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-07 01:35:29,412 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Iniciando actualizaci√≥n del usuario por 'd.email' = 'carlos1006744921@gmail.com'...
2025-05-07 01:35:29,677 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Tabla 'detalle_usuarios' actualizada.
2025-05-07 01:35:29,767 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [GestionLogin.py] Usuario actualizado correctamente con ID 42.
2025-05-07 01:35:29,775 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-07 01:35:29,782 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Transacci√≥n de actualizaci√≥n finalizada.
2025-05-07 01:35:29,789 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-07 01:35:29,799 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Transacci√≥n de eliminaci√≥n finalizada.
2025-05-07 01:35:29,813 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main.py] Cuenta verificada exitosamente.
2025-05-07 01:38:21,400 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-07 01:38:21,401 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-07 01:38:21,406 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Verificando existencia de usuario...
2025-05-07 01:38:21,406 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Verificando existencia de usuario...
2025-05-07 01:38:21,674 - ERROR - Archivo: log.py - L√≠nea: 152 - [ERROR] [main.py] Usuario no encontrado.
2025-05-07 01:38:21,686 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-07 01:38:21,712 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Proceso de login finalizado.
2025-05-07 01:38:22,171 - ERROR - Archivo: log.py - L√≠nea: 152 - [ERROR] [main.py] Contrase√±a incorrecta.
2025-05-07 01:38:22,177 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-07 01:38:22,183 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Proceso de login finalizado.
2025-05-07 01:38:29,677 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-07 01:38:29,681 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Verificando existencia de usuario...
2025-05-07 01:38:30,244 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main.py] Login exitoso.
2025-05-07 01:38:30,248 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-07 01:38:30,252 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Proceso de login finalizado.
2025-05-07 01:38:32,713 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main.py] Sesi√≥n cerrada correctamente.
2025-05-07 01:38:37,856 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-07 01:38:37,866 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Verificando existencia de usuario...
2025-05-07 01:38:38,539 - ERROR - Archivo: log.py - L√≠nea: 152 - [ERROR] [main.py] Contrase√±a incorrecta.
2025-05-07 01:38:38,544 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-07 01:38:38,548 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Proceso de login finalizado.
2025-05-07 01:39:36,368 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Iniciando verificaci√≥n de token...
2025-05-07 01:39:36,378 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Token v√°lido para correo 'carlos1006744921@gmail.com'. Procediendo a activar cuenta...
2025-05-07 01:39:41,927 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-07 01:39:41,932 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Iniciando actualizaci√≥n del usuario por 'd.email' = 'carlos1006744921@gmail.com'...
2025-05-07 01:39:42,190 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Tabla 'detalle_usuarios' actualizada.
2025-05-07 01:39:42,276 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [GestionLogin.py] Usuario actualizado correctamente con ID 42.
2025-05-07 01:39:42,276 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-07 01:39:42,276 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Transacci√≥n de actualizaci√≥n finalizada.
2025-05-07 01:39:42,283 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-07 01:39:42,285 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Transacci√≥n de eliminaci√≥n finalizada.
2025-05-07 01:39:42,287 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main.py] Cuenta verificada exitosamente.
2025-05-07 01:39:49,577 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Iniciando verificaci√≥n de token...
2025-05-07 01:39:49,582 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Token v√°lido para correo 'carlos1006744921@gmail.com'. Procediendo a activar cuenta...
2025-05-07 01:39:55,015 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-07 01:39:55,021 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Iniciando actualizaci√≥n del usuario por 'd.email' = 'carlos1006744921@gmail.com'...
2025-05-07 01:39:55,278 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Tabla 'detalle_usuarios' actualizada.
2025-05-07 01:39:55,366 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [GestionLogin.py] Usuario actualizado correctamente con ID 42.
2025-05-07 01:39:55,371 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-07 01:39:55,379 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Transacci√≥n de actualizaci√≥n finalizada.
2025-05-07 01:39:55,394 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-07 01:39:55,399 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Transacci√≥n de eliminaci√≥n finalizada.
2025-05-07 01:39:55,406 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main.py] Cuenta verificada exitosamente.
2025-05-07 01:40:56,307 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Iniciando verificaci√≥n de token...
2025-05-07 01:40:56,312 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Token v√°lido para correo 'carlos1006744921@gmail.com'. Procediendo a activar cuenta...
2025-05-07 01:41:04,179 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-07 01:41:04,182 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Iniciando actualizaci√≥n del usuario por 'd.email' = 'carlos1006744921@gmail.com'...
2025-05-07 01:41:04,455 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Tabla 'detalle_usuarios' actualizada.
2025-05-07 01:41:04,550 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [GestionLogin.py] Usuario actualizado correctamente con ID 42.
2025-05-07 01:41:04,558 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-07 01:41:04,567 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Transacci√≥n de actualizaci√≥n finalizada.
2025-05-07 01:41:04,575 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-07 01:41:04,586 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Transacci√≥n de eliminaci√≥n finalizada.
2025-05-07 01:41:04,594 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main.py] Cuenta verificada exitosamente.
2025-05-07 01:41:31,905 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-07 01:41:31,908 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Iniciando actualizaci√≥n del usuario por 'd.email' = 'carlos1006744921@gmail.com'...
2025-05-07 01:41:32,370 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Tabla 'detalle_usuarios' actualizada.
2025-05-07 01:41:32,460 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] Usuario actualizado correctamente con ID 42.
2025-05-07 01:41:32,465 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-07 01:41:32,467 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Transacci√≥n de actualizaci√≥n finalizada.
2025-05-07 01:41:32,470 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-07 01:41:32,472 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Transacci√≥n de eliminaci√≥n finalizada.
2025-05-07 01:41:32,473 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] ‚úÖ Usuario actualizado correctamente.
2025-05-07 01:41:33,097 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-07 01:41:33,097 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Iniciando b√∫squeda del usuario por 'u.id_usuario' = '4'...
2025-05-07 01:41:33,269 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] Consulta completada para el id_usuario '4'.
2025-05-07 01:41:33,271 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-07 01:41:33,271 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main_test.py] Finalizaci√≥n de consulta de usuario.
2025-05-07 01:41:33,271 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main_test.py] ‚úÖ Usuario consultado correctamente.
2025-05-07 01:41:52,503 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-07 01:41:52,509 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Verificando existencia de usuario...
2025-05-07 01:41:53,046 - ERROR - Archivo: log.py - L√≠nea: 152 - [ERROR] [main.py] Contrase√±a incorrecta.
2025-05-07 01:41:53,049 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-07 01:41:53,054 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Proceso de login finalizado.
2025-05-07 01:42:03,866 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-07 01:42:03,870 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Verificando existencia de usuario...
2025-05-07 01:42:04,433 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main.py] Login exitoso.
2025-05-07 01:42:04,435 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-07 01:42:04,440 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Proceso de login finalizado.
2025-05-07 01:42:06,169 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Iniciando generaci√≥n de token para correo 'carlos1006744921@gmail.com'...
2025-05-07 01:42:06,175 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Link generado: http://localhost:5000/login/verificar/ImNhcmxvczEwMDY3NDQ5MjFAZ21haWwuY29tIg.aBsAvg.gPA6XtGk5Z0mfXE5qsrs0aXts_w
2025-05-07 01:42:29,795 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main.py] Correo de verificaci√≥n enviado correctamente a 'carlos1006744921@gmail.com'.
2025-05-07 01:42:46,396 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Iniciando verificaci√≥n de token...
2025-05-07 01:42:46,403 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Token v√°lido para correo 'carlos1006744921@gmail.com'. Procediendo a activar cuenta...
2025-05-07 01:42:53,838 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-07 01:42:53,848 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Iniciando actualizaci√≥n del usuario por 'd.email' = 'carlos1006744921@gmail.com'...
2025-05-07 01:42:54,106 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Tabla 'detalle_usuarios' actualizada.
2025-05-07 01:42:54,198 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [GestionLogin.py] Usuario actualizado correctamente con ID 42.
2025-05-07 01:42:54,206 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-07 01:42:54,223 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Transacci√≥n de actualizaci√≥n finalizada.
2025-05-07 01:42:54,255 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-07 01:42:54,267 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Transacci√≥n de eliminaci√≥n finalizada.
2025-05-07 01:42:54,281 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main.py] Cuenta verificada exitosamente.
2025-05-07 01:46:01,090 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Iniciando verificaci√≥n de token...
2025-05-07 01:46:01,092 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Token v√°lido para correo 'carlos1006744921@gmail.com'. Procediendo a activar cuenta...
2025-05-07 01:46:10,537 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-07 01:46:10,541 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Iniciando actualizaci√≥n del usuario por 'd.email' = 'carlos1006744921@gmail.com'...
2025-05-07 01:46:10,801 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Tabla 'detalle_usuarios' actualizada.
2025-05-07 01:46:10,892 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [GestionLogin.py] Usuario actualizado correctamente con ID 42.
2025-05-07 01:46:10,899 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-07 01:46:10,904 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Transacci√≥n de actualizaci√≥n finalizada.
2025-05-07 01:46:10,912 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-07 01:46:10,922 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Transacci√≥n de eliminaci√≥n finalizada.
2025-05-07 01:46:10,939 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main.py] Cuenta verificada exitosamente.
2025-05-07 01:46:39,601 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Iniciando verificaci√≥n de token...
2025-05-07 01:46:39,608 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Token v√°lido para correo 'carlos1006744921@gmail.com'. Procediendo a activar cuenta...
2025-05-07 01:46:49,099 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-07 01:46:49,107 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Iniciando actualizaci√≥n del usuario por 'd.email' = 'carlos1006744921@gmail.com'...
2025-05-07 01:46:49,374 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Tabla 'detalle_usuarios' actualizada.
2025-05-07 01:46:49,467 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [GestionLogin.py] Usuario actualizado correctamente con ID 42.
2025-05-07 01:46:49,474 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-07 01:46:49,483 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Transacci√≥n de actualizaci√≥n finalizada.
2025-05-07 01:46:49,513 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-07 01:46:49,533 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Transacci√≥n de eliminaci√≥n finalizada.
2025-05-07 01:46:49,542 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main.py] Cuenta verificada exitosamente.
2025-05-07 01:47:40,614 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Iniciando verificaci√≥n de token...
2025-05-07 01:47:40,615 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Token v√°lido para correo 'carlos1006744921@gmail.com'. Procediendo a activar cuenta...
2025-05-07 01:47:49,695 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-07 01:47:49,704 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Iniciando actualizaci√≥n del usuario por 'd.email' = 'carlos1006744921@gmail.com'...
2025-05-07 01:47:49,968 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Tabla 'detalle_usuarios' actualizada.
2025-05-07 01:47:50,064 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [GestionLogin.py] Usuario actualizado correctamente con ID 42.
2025-05-07 01:47:50,079 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-07 01:47:50,097 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Transacci√≥n de actualizaci√≥n finalizada.
2025-05-07 01:47:50,114 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-07 01:47:50,120 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Transacci√≥n de eliminaci√≥n finalizada.
2025-05-07 01:47:50,125 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main.py] Cuenta verificada exitosamente.
2025-05-07 02:09:39,361 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-07 02:09:39,367 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Verificando existencia de usuario...
2025-05-07 02:09:39,955 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main.py] Login exitoso.
2025-05-07 02:09:39,961 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-07 02:09:39,971 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Proceso de login finalizado.
2025-05-07 02:10:59,561 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-07 02:10:59,568 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Verificando existencia de usuario...
2025-05-07 02:11:00,222 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main.py] Login exitoso.
2025-05-07 02:11:00,225 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-07 02:11:00,230 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Proceso de login finalizado.
2025-05-07 02:39:33,495 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main.py] Sesi√≥n cerrada correctamente.
2025-05-07 02:39:52,039 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-07 02:39:52,047 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Verificando existencia de usuario...
2025-05-07 02:39:52,749 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main.py] Login exitoso.
2025-05-07 02:39:52,755 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-07 02:39:52,760 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Proceso de login finalizado.
2025-05-07 02:40:01,262 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main.py] Sesi√≥n cerrada correctamente.
2025-05-07 02:40:25,646 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-07 02:40:25,651 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Verificando existencia de usuario...
2025-05-07 02:40:26,198 - ERROR - Archivo: log.py - L√≠nea: 152 - [ERROR] [main.py] Contrase√±a incorrecta.
2025-05-07 02:40:26,202 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-07 02:40:26,207 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Proceso de login finalizado.
2025-05-07 02:40:40,621 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-07 02:40:40,627 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Verificando existencia de usuario...
2025-05-07 02:40:41,283 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main.py] Login exitoso.
2025-05-07 02:40:41,294 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-07 02:40:41,323 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Proceso de login finalizado.
2025-05-07 02:46:15,933 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main.py] Sesi√≥n cerrada correctamente.
2025-05-07 02:46:27,441 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-07 02:46:27,446 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Verificando existencia de usuario...
2025-05-07 02:46:28,006 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main.py] Login exitoso.
2025-05-07 02:46:28,011 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-07 02:46:28,016 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Proceso de login finalizado.
2025-05-07 02:48:31,987 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-07 02:48:31,993 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Verificando existencia de usuario...
2025-05-07 02:48:32,572 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main.py] Login exitoso.
2025-05-07 02:48:32,576 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-07 02:48:32,582 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Proceso de login finalizado.
2025-05-07 02:48:52,718 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-07 02:48:52,723 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Iniciando b√∫squeda del usuario por 'u.nick_name' = 'Carlos_CJ'...
2025-05-07 02:48:52,908 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main.py] Consulta completada para el id_usuario 'Carlos_CJ'.
2025-05-07 02:48:52,917 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-07 02:48:52,944 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Finalizaci√≥n de consulta de usuario.
2025-05-07 02:48:54,121 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-07 02:48:54,124 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Iniciando actualizaci√≥n del usuario por 'u.nick_name' = 'Carlos_CJ'...
2025-05-07 02:48:54,857 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Tabla 'detalle_usuarios' actualizada.
2025-05-07 02:48:54,948 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main.py] Usuario actualizado correctamente con ID 42.
2025-05-07 02:48:54,952 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-07 02:48:54,958 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Transacci√≥n de actualizaci√≥n finalizada.
2025-05-07 02:48:54,964 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [Crud_Usuario_Detalle.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-07 02:48:54,970 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Transacci√≥n de eliminaci√≥n finalizada.
2025-05-07 02:49:49,203 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main.py] Sesi√≥n cerrada correctamente.
2025-05-07 02:50:06,879 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-07 02:50:06,887 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Verificando existencia de usuario...
2025-05-07 02:50:07,593 - ERROR - Archivo: log.py - L√≠nea: 152 - [ERROR] [main.py] Contrase√±a incorrecta.
2025-05-07 02:50:07,593 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-07 02:50:07,601 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Proceso de login finalizado.
2025-05-07 02:50:31,429 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-07 02:50:31,431 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Verificando existencia de usuario...
2025-05-07 02:50:31,833 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main.py] Login exitoso.
2025-05-07 02:50:31,833 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-07 02:50:31,833 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Proceso de login finalizado.
2025-05-07 02:50:45,014 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main.py] Sesi√≥n cerrada correctamente.
2025-05-07 02:51:01,142 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-07 02:51:01,142 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-07 02:51:01,148 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Verificando existencia de usuario...
2025-05-07 02:51:01,148 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Verificando existencia de usuario...
2025-05-07 02:51:01,409 - ERROR - Archivo: log.py - L√≠nea: 152 - [ERROR] [main.py] Usuario no encontrado.
2025-05-07 02:51:01,415 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-07 02:51:01,432 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Proceso de login finalizado.
2025-05-07 02:51:01,832 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main.py] Login exitoso.
2025-05-07 02:51:01,836 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-07 02:51:01,838 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Proceso de login finalizado.
2025-05-07 02:51:18,636 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-07 02:51:18,640 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Verificando existencia de usuario...
2025-05-07 02:51:19,161 - ERROR - Archivo: log.py - L√≠nea: 152 - [ERROR] [main.py] Contrase√±a incorrecta.
2025-05-07 02:51:19,165 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-07 02:51:19,179 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Proceso de login finalizado.
2025-05-07 02:51:34,451 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-07 02:51:34,451 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Verificando existencia de usuario...
2025-05-07 02:51:34,869 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main.py] Login exitoso.
2025-05-07 02:51:34,879 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-07 02:51:34,881 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Proceso de login finalizado.
2025-05-07 02:53:22,204 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main.py] Sesi√≥n cerrada correctamente.
2025-05-07 02:54:55,343 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-07 02:54:55,347 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Verificando existencia de usuario...
2025-05-07 02:54:55,903 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main.py] Login exitoso.
2025-05-07 02:54:55,907 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-07 02:54:55,910 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Proceso de login finalizado.
2025-05-07 02:55:07,102 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main.py] Sesi√≥n cerrada correctamente.
2025-05-07 02:56:00,032 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-07 02:56:00,038 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Verificando existencia de usuario...
2025-05-07 02:56:00,639 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main.py] Login exitoso.
2025-05-07 02:56:00,645 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-07 02:56:00,650 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Proceso de login finalizado.
2025-05-07 02:58:50,072 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-07 02:58:50,079 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Verificando existencia de usuario...
2025-05-07 02:58:50,802 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main.py] Login exitoso.
2025-05-07 02:58:50,809 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-07 02:58:50,815 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Proceso de login finalizado.
2025-05-07 02:58:57,396 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main.py] Sesi√≥n cerrada correctamente.
2025-05-07 03:14:12,177 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-07 03:14:12,181 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Verificando existencia de usuario...
2025-05-07 03:14:12,746 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main.py] Login exitoso.
2025-05-07 03:14:12,752 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-07 03:14:12,766 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Proceso de login finalizado.
2025-05-07 03:15:21,208 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main.py] Sesi√≥n cerrada correctamente.
2025-05-07 03:15:42,536 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n establecida exitosamente con la base de datos PostgreSQL.
2025-05-07 03:15:42,539 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Verificando existencia de usuario...
2025-05-07 03:15:43,187 - INFO - Archivo: log.py - L√≠nea: 193 - [SUCCESS] [main.py] Login exitoso.
2025-05-07 03:15:43,194 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [GestionLogin.py] Conexi√≥n con la base de datos cerrada correctamente.
2025-05-07 03:15:43,199 - INFO - Archivo: log.py - L√≠nea: 126 - [INFO] [main.py] Proceso de login finalizado.
